const scribbleWords = [
  "Waterfall",
  "Spaceship",
  "Lighthouse",
  "Kangaroo",
  "Pyramids",
  "Rainbow",
  "Skateboard",
  "Volcano",
  "Scarecrow",
  "Cactus",
  "Butterfly",
  "Sailboat",
  "Penguin",
  "Snowflake",
  "Campfire",
  "Dragon",
  "Balloon",
  "Smartphone",
  "Teapot",
  "Bookshelf",
  "Binoculars",
  "Windmill",
  "Mushroom",
  "Sneakers",
  "Telescope",
  "Birdhouse",
  "Unicorn",
  "Toaster",
  "Hourglass",
  "Sunflower",
  "Paintbrush",
  "Jellyfish",
  "Boomerang",
  "Microphone",
  "Lemon",
  "Rocket",
  "Airplane",
  "Ice Cream",
  "Saxophone",
  "Pineapple",
  "Hamburger",
  "Snowman",
  "Seashell",
  "Popcorn",
  "Ladder",
  "Disco Ball",
  "Dessert",
  "Suitcase",
  "Sunglasses",
  "Candy Cane",
  "Microscope",
  "Hammock",
  "Coconut",
  "Compass",
  "Octopus",
  "Violin",
  "Watermelon",
  "Megaphone",
  "Fireworks",
  "Fireplace",
  "Snowboard",
  "Pumpkin",
  "Pizza",
  "Wheelbarrow",
  "Helicopter",
  "Submarine",
  "Cupcake",
  "Trumpet",
  "Wrench",
  "Grass",
  "Teddy Bear",
  "Lantern"
];

export default scribbleWords;